### ISSUE TITLE
Astro.build Vue Error

### ISSUE THREAD

**Issue by roblevintennis** [AgnosticUI/agnosticui#138]
I did a test using Astro and the React and Svelte packages loaded fine but the Vue package threw errors re not being a proper es module or named .mjs. Will gather proper errors when back at a computer.

Should try building vue package with `type: "module"` and also try bringing in Astro as a test app and comment things out until we can figure out what/why we're getting failure.

```shell
➜  astro npm run dev

> @example/starter@0.0.1 dev
> astro dev

  🚀  astro  v0.24.3 started in 349ms
  
  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose
  
7:41:38 AM [vite] Failed to load source map for /node_modules/agnostic-react/dist/esm/index.css.
[Vue warn]: Failed to resolve component: Button
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
07:41:39 AM [serve] 500    /
07:41:39 AM [error] TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (/Users/roblevin/workspace/opensource/misc/astro/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3345:15)
    at createComponentInstance (/Users/roblevin/workspace/opensource/misc/astro/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6851:23)
    at renderComponentVNode (/Users/roblevin/workspace/opensource/misc/astro/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:197:22)
    at Proxy.ssrRenderComponent (/Users/roblevin/workspace/opensource/misc/astro/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:629:12)
    at _sfc_ssrRender (/src/components/VueCounter.vue:43:31)
    at renderComponentSubTree (/Users/roblevin/workspace/opensource/misc/astro/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:269:13)
    at renderComponentVNode (/Users/roblevin/workspace/opensource/misc/astro/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)
    at renderVNode (/Users/roblevin/workspace/opensource/misc/astro/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:310:22)
    at renderComponentSubTree (/Users/roblevin/workspace/opensource/misc/astro/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:275:13)
```

There was another error I can't repro at the moment but message was:
```shell
package doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
```

**Comment by roblevintennis** [comment]
NTS Astro docs on adding vue integration are misleading atm. This helped
https://stackblitz.com/github/withastro/astro/tree/latest/examples/framework-vue?file=README.md

```shell
npm init astro -- --template framework-vue
```

I'm trying to repro in agnosticui locally in `agnostic-vue/example_astro`

```shell
npm i ../agnostic-vue-1.0.19.tgz
```

**Comment by roblevintennis** [comment]
May be able to work around this by importing the `src/*` modules directly and including the file extension

**Comment by roblevintennis** [comment]
Working now -- https://github.com/AgnosticUI/agnosticui/tree/master/agnostic-vue/example_astro
